version: '3.7'

services:
  events_api:
    environment:
      - MONGO_URL=mongodb://db:27017
    build:
      context: .
      dockerfile: ./events-api/Dockerfile
    hostname: events-api
    ports:
      - "8000:8000"
  files_api:
    environment:
      - MONGO_URL=mongodb://db:27017
    build:
      context: .
      dockerfile: ./filesapi/Dockerfile
    hostname: filesapi
    ports:
      - "8001:8001"
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: db
    volumes:
      - ./mongo_data:/data/db
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis
    hostname: redis
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    container_name: prometheus
    hostname: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    container_name: grafana
    volumes:
      - ./grafana_data:/var/lib/grafana



